### ISSUE TITLE
Assigning times in defer dates

### ISSUE THREAD

**Issue by brandonpittman** [lemonmade/templates#16]
Is there a way to assign a time for the current day in defer dates? If I use `ask` and give it 5pm it sets it to "5pm", but if I set `defer: 5pm` it gets set to "9am" of the current day.

**Comment by distantnative** [comment]
Any progress on the date parsing?

**Comment by brandonpittman** [comment]
If I set it to `17h`, I get close to what I want — I get 4:59PM.
