### ISSUE TITLE
Complete licence

### ISSUE THREAD

**Issue by GitBruno** [lemonmade/templates#29]
At the moment the licence looks like this (correct?):

> Copyright (c) 2013 - 2014, Chris Sauvé
> Use it, change it, repackage it, whatever. Try not to take credit for my work.

Do you meant to put it in the public domain? Or a BSD licence more suitable?

Either way, a proper licence makes it easier for people to use, change and repackage it.

**Comment by lemonmade** [comment]
Thanks for the issue. I've updated to use MIT, and took the opportunity to leave a note in the README that I am no longer actively maintaining the script. Hopefully this will make it easy for anyone else to change this in whatever way works best for them.

**Comment by GitBruno** [comment]
Awesome, thanks! May I ask you what the reason for not maintaining it is? Did you find a better tool/script?

**Comment by lemonmade** [comment]
I haven't used OmniFocus in a long time (nothing against OmniFocus at all, my job just ended up involving a completely separate workflow for managing most tasks). I also don't have as much time as I would like to dedicate to OSS anymore, unfortunately.
